[mgr]
prepend_keymap = [
  # Default yazi
    { on = "!", run = 'shell "$SHELL" --block', desc = "Open $SHELL here", for  = "unix" },
    { on = "!", run = 'shell "pwsh.exe" --block', desc = "Open PowerShell 7 here", for  = "windows" },
    { on = "<Esc>", run = 'close', desc = "Cancel input", for  = "windows" },

  # Default Plugin
	{ on = "z", run = "plugin zoxide", desc = "Jump to a directory via zoxide" },
	{ on = "Z", run = "plugin fzf",    desc = "Jump to a file/directory via fzf" },

  # In Plugin
    { on = "<Enter>", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
    { on = "T", run = "plugin toggle-pane min-preview", desc = "Show or hide the preview pane" },
    { on = "T", run = "plugin toggle-pane max-preview", desc = "Maximize or restore the preview pane" },
]