[mgr]
show_hidden = true

# プラグイン
[plugin]
prepend_previewers = [
    { mime = "audio/*",   run = "exifaudio"}
]

[opener]
edit = [
    { run = '${EDITOR:-vi} "$@"', desc = "$EDITOR", block = true, for = "unix" },
    { run = 'nvim "%*"', block = true, desc = "nvim", for = "windows" },
    { run = 'micro "%*"', block = true, desc = "micro", for = "windows" },
    { run = 'code %*', orphan = true, desc = "code", for = "windows" },
]
image = [
    { run = 'mpv --force-window "$@"', orphan = true, for = "unix" },
    { run = 'mpv --force-window %*', orphan = true, for = "windows" },
]
video_play = [
    { run = 'mpv --force-window "$@"', orphan = true, for = "unix" },
    { run = '''mediainfo "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show media info", for = "unix" },
    { run = 'mpv --force-window %*', orphan = true, for = "windows" },
]
music_backplay = [
    { run = 'sap -i %*', desc = "Background Play", for = "windows" },
]
music_play = [
    { run = 'mpv --force-window "$@"', orphan = true, for = "unix" },
    { run = '''mediainfo "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show media info", for = "unix" },
    { run = 'sap -i %*', block = true, for = "windows" },
    { run = 'mpv --force-window %*', orphan = true, for = "windows" },
]
txt_edit = [
    { run = 'edit "%*"', block = true, desc = "edit", for = "windows" },
]

[open]
prepend_rules = [
    { name = "*.txt", use = "txt_edit" },
    { name = "*.ogg", use = "music_backplay" },
]
rules = [
# Folder #
    { name = "*/", use = [ "edit", "open", "reveal" ] },
    # Text
    { mime = "text/*", use = [ "edit", "reveal" ] },
    # Image
    { mime = "image/*", use = [ "image", "reveal" ] },
    # Media / Audio
    { mime = "audio/*", use = [ "music_play", "reveal" ] },
    # Media / Video
    { mime = "video/*", use = [ "video_play", "reveal" ] },
    # Archive
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [ "open", "reveal" ] },
    # Empty file
    { mime = "inode/empty", use = [ "edit", "reveal" ] },
    # Fallback
    { name = "*", use = [ "open", "reveal" ] },
]
append_rules = [

]
